### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by RolfDeVries** [amsify42/jquery.amsify.suggestags#10]
Can you please provide an npm package.json file, so we can include the package in out ci pipeline

**Comment by amsify42** [comment]
Creating only package.json will do the job 
Or
do I need to make any changes to my code along with the package.json?

I am asking because I have a very little idea about how to make jquery plugin available through npm?

**Comment by RolfDeVries** [comment]
Code changes are not nessesari. See this article
https://docs.npmjs.com/creating-node-js-modules

**Comment by amsify42** [comment]
Thanks
I'll check the article, add package.json and update you here.

**Comment by amsify42** [comment]
Added package.json file to the plugin and updated.
