### ISSUE TITLE
Disable hover behavoir

### ISSUE THREAD

**Issue by RolfDeVries** [amsify42/jquery.amsify.suggestags#11]
Hi, first of all I very much like you're plugin!

When I have the suggestionlist open and my mouse is over a suggestion its automaticly selected. This is nice, but when i start typing al kinds of strange thing happen, because of the hover behavior.

I fixed this by commenting out the hover behavior 
`//$(_self.selectors.sTagsInput).val($(this).data('val'));`

Can you please provide a setting for this, so I don't have to override the code.

Thank you very much!

**Comment by amsify42** [comment]
I have added select on hover setting, by default it is true make it false like this:
`selectOnHover: false`
