### ISSUE TITLE
$item.data(...).toLowerCase is not a function

### ISSUE THREAD

**Issue by jaberu** [amsify42/jquery.amsify.suggestags#12]
Having this isse when I use numbers as suggestions. Doesnt matter if I use (single/double) quotes or not.

In that case the input text component returns a number instead of a string. 
```
$('input[id="createDataTypeForm:dataTypeProcedures"]').amsifySuggestags({
            type : 'amsify',
            suggestions: ["10", "20", "sdfg"],
            classes: ["tag-procedure", "tag-procedure", "tag-procedure"]
});
```

Occurs with Chrome and IE

**Comment by jaberu** [comment]
Seems to be standard behaviour of the data() function.
Following fix worked for me:
https://github.com/amsify42/jquery.amsify.suggestags/pull/13

**Comment by amsify42** [comment]
Thanks for the fix. I will merge the pull request and check it.
