### ISSUE TITLE
The default class for the tag

### ISSUE THREAD

**Issue by Mativve** [amsify42/jquery.amsify.suggestags#15]
Hi!

Is it possible to set a default class for a tag that is not in the 'suggest' and 'classes' array?
I want to use Bootstrap badge style.

When I load data from JSON file I set suggestion and classes params - and this works.

I use Booststrap 4.3.1 and in params I set type to 'bootstrap' but this not help.

Maybe it is possible to add a parameter with the default class for the tag? It would be great!

![screen](https://user-images.githubusercontent.com/17256874/62117555-6f280400-b2bc-11e9-838e-c39221cfdfa9.png)

Greetings
Mateusz

PS: Cool and simple plugin ;)

EDIT/1

Now I'm using this script to get this effect, but it will be easier if it's in params ;)
```javascript
$.ajax({
    url: "assets/categories.json",
    dataType: 'json',
    cache: false
}).done((res) => {
    const sugg = res.map(function(e) {
        return e.text;
    });
    const sugg_cls = res.map(function(e) {
        return e.classes;
    });

    elt.amsifySuggestags({
        type: 'bootstrap',
        suggestions: sugg,
        classes: sugg_cls,
        tagLimit: 50,
        afterAdd: function(value) {
            if (!sugg.includes(value)) {
                $(`span[data-val="${value}"]`).addClass("badge badge-primary");
            }
        }
    });
});
```

**Comment by amsify42** [comment]
Hi,
Thanks for your suggestion. I have added the mentioned setting with name **defaultTagClass**.
Please check here
https://github.com/amsify42/jquery.amsify.suggestags#custom-stylings

**Comment by Mativve** [comment]
@amsify42 Cool, this is what I ment! Thank you! :)
