### ISSUE TITLE
If suggestion tag not found then show placeholder text possible ?

### ISSUE THREAD

**Issue by mitulmarsonia** [amsify42/jquery.amsify.suggestags#17]
Thanks for make great library.

Tag suggestion and new tag creation working properly. I want if no tag suggestion as per our search then we want to show bottom placeholder "Enter to generate new tag".

Please help me out.

**Comment by amsify42** [comment]
Okay, I will try to add some setting option for this, update the code and let you know.

**Comment by amsify42** [comment]
I have added a setting with name `noSuggestionMsg`, you can pass it something like this
```
$('input[name="color"]').amsifySuggestags({
	noSuggestionMsg: 'Enter to generate new tag'
});
```
