### ISSUE TITLE
Modify an input tags

### ISSUE THREAD

**Issue by TOUTOUDOUDOU** [amsify42/jquery.amsify.suggestags#18]
Hi,
I want to know how I can solve this problem:
- I created a set of input tags with a set of suggestions ("group_1", "group_2" and "group_3")
- I want to know how can I refresh all the inputs created (add/remove a suggestion/tag)
I tested this code:
$('input[name^="group_"]').amsifySuggestags().addTag('example');
but nothing is changed

**Comment by amsify42** [comment]
I want to understand what exactly you are trying to do here. You are creating n number of inputs and initializing this plugin for each.
From where you are getting this `inputValue` variable? Is it from some event?
