### ISSUE TITLE
Tag List not visible

### ISSUE THREAD

**Issue by Talkenberger** [amsify42/jquery.amsify.suggestags#19]
Hello,

the plugin is lonely top ;-)
Unfortunately I have a small problem and hope for help.

Stand Alone, everything works smoothly. But as soon as I apply the plugin to an input in a JQuery UI dialog, the taglist is no longer visible.

I have to understand two small fiddles created.

Here without dialogue -> all OK
https://jsfiddle.net/Talki/em5d9Lf6/7/

Here with dialogue ...
https://jsfiddle.net/Talki/xzc9a3s7/31/

I hope the problem is relatively easy to solve ;-)

Thanks in advance

Klaus Talkenberger

**Comment by amsify42** [comment]
Thank you.

I have checked your code with dialogue, in developer tool I am able to see that width of element with class `amsify-suggestags-list` becoming zero for some reason, you can try assigning the width of input size to this class or hard code the width in some css file for the same class.

Hope it will help you.

**Comment by amsify42** [comment]
I am closing this issue, I hope my last comment will help you.
