### ISSUE TITLE
Add a tag Programmatically

### ISSUE THREAD

**Issue by TOUTOUDOUDOU** [amsify42/jquery.amsify.suggestags#20]
Hi
I want to add a tag to a created and intialized input tags programmatically. I know that I can use addTag() with instance of AmsifySuggestags, but I do not know how I can retrieve the corresponding  instance of AmsifySuggestags of the created input.
I tried:
$('input[name="country"]').amsifySuggestags().addTag('xxx')
but no result

**Comment by amsify42** [comment]
Actually the only way to add tag programmatically is by creating each instance of input like this
```
amsifySuggestags = new AmsifySuggestags($('input[name="country"]'));
amsifySuggestags._init();
amsifySuggestags.addTag('xxx');
```
You cannot use this initialization to add tag programmatically
`$('input[name="country"]').amsifySuggestags();`

**Comment by TOUTOUDOUDOU** [comment]
thank you,
I have another question
Can I attach other hidden informations to the texts of tags. For example, using a select list,
we assign to each option a text that appears in the list and a real value in the value attribute.
Can I do the same thing with the tags?

**Comment by amsify42** [comment]
Currently it does not have any such option. I will try to add this option and update here in this thread.

**Comment by TOUTOUDOUDOU** [comment]
thank you

**Comment by amsify42** [comment]
I have added a way to set tags with their respective values. you can set suggestions like this
```js
$('input[name="color"]').amsifySuggestags({
	suggestions: [
					{'tag': 'Black', 'value': 1},
					{'tag': 'White', 'value': 2},
					{'tag': 'Red', 'value': 3},
					{'tag': 'Blue', 'value': 4},
					{'tag': 'Green', 'value': 5},
					{'tag': 'Orange', 'value': 6},
				]
});
```

Here these will appear as tags
```txt
Black
White
Red
Blue
Green
Orange
```
and the value will be submitted to form.

Lets say, if you select `White` and `Blue` tags then input will have their values separated by comma
`2,4`

Please let me know if its working fine.
