### ISSUE TITLE
Why Post instead of Get for ajax suggestions?

### ISSUE THREAD

**Issue by codertimu** [amsify42/jquery.amsify.suggestags#22]
I just wonder why Post was preferred instead of Get for ajax call. I think it should be a simple get query with just a search term. Why do we have to send existing suggestions? I believe that the merging of suggestions should be done after the query locally.

**Comment by amsify42** [comment]
Thanks for your question and it is a good one.
The idea which made me put it as POST is, when we pass search term and existing items in request, I wanted to make sure that I don't load existing items from server again.

**Comment by codertimu** [comment]
You are already merging ajax results with current suggestions and making them unique. I don't think it is necessary to send existing tags, this is a subtle optimization.
The reason why I am insisting on this issue so much is that I can't change the web service I am using for suggestions from Get to Post. And I am still in the opinion that this should not be a Post request.

**Comment by amsify42** [comment]
Okay, I will change the POST to GET, push/publish in next update and let you know here.

**Comment by codertimu** [comment]
Thank you. People who want this optimization can still pass existing tags as query parameters to their GET service and handle it in their service.

**Comment by amsify42** [comment]
Yes, I hope it will not cause a major changing issue for other people who are using ajax suggestions.

**Comment by amsify42** [comment]
Changed **POST** to **GET** for ajax suggestions and published the package. Please let me know its working for you then I can close the issue.
