### ISSUE TITLE
Option to show white list suggestions before User has entered any characters?

### ISSUE THREAD

**Issue by ProductiveRage** [amsify42/jquery.amsify.suggestags#23]
If I have a relatively small list of suggestions and if the User might not know what all of the options are, it would be great if there was a way to configure the input so that the suggestions drop down is displayed even before they have entered any characters. Maybe it would show the drop down as soon as focus enters the input or as soon as one token has been selected and they need to move on to the next one; or maybe it could show the dropdown if the User presses the down cursor key when they start a new token, rather than pressing a character that is expected to be matched within a white list entry?

Does anything like this exist already?

**Comment by ProductiveRage** [comment]
Never mind, I've been able to make it do this by returning all values through the "completionsForText" callback if it's called with a blank text string.

(In case anyone else finds it useful in the future, I've got a jsfiddle based upon a cutdown version of the demo.html code from this repo; [jsfiddle.net/rmu7bsv2/](https://jsfiddle.net/rmu7bsv2/))

**Comment by ProductiveRage** [comment]
(I closed this a few minutes ago with a comment saying that I'd found a solution based upon the demos included in this repo but then I realised that I'd done it with _another_ library - sorry! So my question still stands :)

**Comment by amsify42** [comment]
Currently it does not show all suggestions before user enter something. I will add some setting for it, publish the code and let you know here.

**Comment by lievcin** [comment]
👍

**Comment by amsify42** [comment]
I have added this option `showAllSuggestions` in settings, you can pass it as `true` to make it work.
```js
showAllSuggestions: true
```

**Comment by lievcin** [comment]
I can't find a way of hidding the options once triggered. I'll open an issue for this.
