### ISSUE TITLE
Issue with suggestions list width

### ISSUE THREAD

**Issue by gioele-santi** [amsify42/jquery.amsify.suggestags#31]
Hi I am using this library in a couple of pages in a project.
When I used it the first time, everything was fine but then I needed to add another tag field in a different page with the same suggestions code.

So I replicated the same configuration in the second page, but this time when suggestions appear, the width of the panel is set to 0px. Everything else is fine, but I can't find a way to fix the width. Could it depend on other html tags surrounding the text input?

The code in the page:

```
<div class="row">
     <div class="col-12 pb-1 pb-lg-0">
           <input type="text" class="form-control" name="caselawTag"/>
    </div>
</div>
```

and javascript: 

```
    $(document).ready(function () {
        $('input[name="caselawTag"]').amsifySuggestags({
            whiteList: true, 
            suggestionsAction : {
                url: '{{ @SCHEME."://".@HOST.@BASE."/tag/suggestions" }}'
            }
        });
        
      // some other stuff ...
        
    });
```

The URL is generated by php templating engine, it works fine.

Any help or suggestion would be nice.

**Comment by amsify42** [comment]
Looks like some css issue, Finding an issue just by seeing what you mentioned is difficult. If you could add your code to jsfiddle or somewhere and send me link, that might help us to know the issue and its solution.
