### ISSUE TITLE
ajax suggestion not working

### ISSUE THREAD

**Issue by ABTanjir** [amsify42/jquery.amsify.suggestags#32]
I have followed your documentation properly and returning json properly, but suggestion is not appearing

**Comment by amsify42** [comment]
To know the issue and its solution, you should put your code in your comment.

**Comment by eailyass** [comment]
Also the same issue for me!
I put this response in my php code:
`return new JsonResponse(['India', 'Pakistan', 'Nepal', 'UAE', 'Iran', 'Bangladesh']`

On JS I use:
```
suggestionsAction: {
        url: //my url,
        success: function(data) {
            console.info(data);
        }

```
On my page, I get the correct result on console, but nothing is shown in the input!

**Comment by amsify42** [comment]
I checked on my local pc, its working fine. Make sure when you are sending a json response through any server side script, you are also sending proper header of json.

Example for PHP, we send this json header.
```
header('Content-Type: application/json');
```

**Comment by scdigitalmedia** [comment]
I'm having this same issue. Headers are set to application/json as well. My output is "["tires","quote"]". When I hardcode that into the suggestions it works perfect. when I use Ajax it doesn't work.
