### ISSUE TITLE
Installation on local PC not working

### ISSUE THREAD

**Issue by KDMortimer** [amsify42/jquery.amsify.suggestags#33]
Hi there,
This is probably some silly mistake I am making because I am still comparatively new at modern web development. So hopefully just a quick fix or me missing something...

I have downloaded this repo for testing a design-in-progress on my local machine, but I haven't been able to get it working. I don't see any errors in my developer console and can navigate in-browser through the CSS and JS of the project - it just doesn't seem to do anything. Even with values added, it just appears as plain text on the page, rather than as tags - see below.

![tagproblem](https://user-images.githubusercontent.com/43451442/71015463-048c2f00-20ca-11ea-94ed-b1a2e57f28f8.PNG)

I've reproduced the minimal HTML I'm using below - the amsify.suggestags repo is in the suggestags folder, which is in the same folder as this HTML file. 

```
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="suggestags/css/amsify.suggestags.css">
    <title>Test</title>
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="suggestags/js/jquery.amsify.suggestags.js"></script>
    <script>
      $('input[name="topics"]').amsifySuggestags({
      suggestions: ['farming', 'biota', 'boundaries', 'climatologyMeteorologyAtmosphere', 'economy', 'elevation'],
      whiteList: true
    });
    </script>
    <input type="text" class="form-control" name="topics" value="biota,farming"/><br/>

  </body>
</html>
```
Thanks!

**Comment by amsify42** [comment]
You can either do this
```js
$(document).ready(function(){
  $('input[name="topics"]').amsifySuggestags({
    suggestions: ['farming', 'biota', 'boundaries', 'climatologyMeteorologyAtmosphere', 'economy', 'elevation'],
    whiteList: true
  });
});
```
or keep the plugin initialization below the input
```html
<input type="text" class="form-control" name="topics" value="biota,farming"/><br/>
<script type="text/javascript">
  $('input[name="topics"]').amsifySuggestags({
    suggestions: ['farming', 'biota', 'boundaries', 'climatologyMeteorologyAtmosphere', 'economy', 'elevation'],
    whiteList: true
  });
</script>
```
And the slim version of the jquery you are using causing some issue while removing tag item in the plugin, you can use this jquery cdn to fix it.
```html
<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
```

**Comment by KDMortimer** [comment]
Thank you for the prompt reply. While playing around just now I discovered I needed to have the script *below* the input, which was entirely the problem...

Also worth noting that I needed to add the styleshet for font-awesome to get everything working perfectly. (In case anyone else comes here looking for help with a similar problem).
