### ISSUE TITLE
Objects through Ajax

### ISSUE THREAD

**Issue by luizz** [amsify42/jquery.amsify.suggestags#34]
Hello, 
how can I get suggestions as objects through Ajax ? 
I have a lot of repeated items in the suggestions list.
This is the modified suggestions.php file 

```
<?php
$suggestions 	= [['tag'=>'India','value'=>34], ['tag'=>'Pakistan','value'=>12], ['tag'=>'Nepal','value'=>43], ['tag'=>'UAE','value'=>11], ['tag'=>'Iran','value'=>21], ['tag'=>'Bangladesh','value'=>22],['tag'=>'Italy','value'=>23], ['tag'=>'Australia','value'=>134]];

$data 			= [];

foreach($suggestions as $suggestion)
{
	if(strpos(strtolower($suggestion['tag']), strtolower($_GET['term'])) !== false)	{
		$data[] = $suggestion;	
	}
}

header('Content-Type: application/json');
echo json_encode(['suggestions' => $data]);
```

**Comment by amsify42** [comment]
Sorry for the late response and thanks for letting me know the issue. I have fixed it and published the latest version. Please check and confirm.

**Comment by luizz** [comment]
It works fine, thank you !
For initialization I set the value attribute to IDs 

``<input type="text" class="form-control" name="toAjax" value="India,Pakistan"/>``

and populate suggestions

```
$('input[name="toAjax"]').amsifySuggestags({
           suggestions: [
		{tag: 'India', value: 34},
		{tag: 'Pakistan', value: 12},
           ],
	   suggestionsAction : {
		url : 'jquery-plugins/suggestags/examples/suggestions.php'
	   }
});
```

Is that right ?

**Comment by amsify42** [comment]
No, input should have actual values separated by comma not tag names.
```html
<input type="text" class="form-control" name="toAjax" value="34,12"/>
```

**Comment by luizz** [comment]
This works with objets, but not with objets through Ajax.
I tried, but this way the field contains the numbers.

**Comment by amsify42** [comment]
Since, you are setting default value and using ajax, not only you need to set the actual value in html input.
```html
<input type="text" class="form-control" name="toAjax" value="34,12"/>
```

**Comment by luizz** [comment]
It's all clear now.
Thank you very much for your great work and for your time.
