### ISSUE TITLE
No flag to disable: printValues

### ISSUE THREAD

**Issue by Madpeterz** [amsify42/jquery.amsify.suggestags#36]
There is no flag to disable printValues leading to the console being spammed.

file: js\jquery.amsify.suggestags.js
line:  589

work around: Comment out of the console.info.
// console.info(this.tagNames, $(this.selector).val());

**Comment by amsify42** [comment]
Okay, I will add the option for this, update the code and let you know here.

**Comment by amsify42** [comment]
Added the option and published
