### ISSUE TITLE
suggestionsAction lacking controls

### ISSUE THREAD

**Issue by Madpeterz** [amsify42/jquery.amsify.suggestags#37]
some extra options for suggestionsAction would be nice:

for example
- rate-limit:  amount of time (in ms) before allowing a new call to the url
                   defaults to: -1 (ignored)
- min-chars: the lowest amount of letters before making a call to the url
                   defaults to: 3
- min-change: the lowest amount of changed letters before repeating a call to the url
                   defaults to: -1 (ignored)

**Comment by amsify42** [comment]
Thank you for suggestion, I will add these settings.

**Comment by amsify42** [comment]
Added the options but with different key names, please check and confirm whether is it as you suggested or not.
