### ISSUE TITLE
bug/request with processAjaxSuggestion

### ISSUE THREAD

**Issue by Madpeterz** [amsify42/jquery.amsify.suggestags#38]
function: processAjaxSuggestion
uses this.settings.suggestions as the source of existing items 
but this does not include items already loaded for example

```<input type="text" value="Act,Once,Check,Twice">```

only the current input term is sent.

workaround:
add: current: this.tagNames.join(", ")
before: existing: this.settings.suggestions
on line: 254

**Comment by amsify42** [comment]
Thanks, I will try to make changes as mentioned, test and update you here.

**Comment by amsify42** [comment]
Added the key, but with name `existingTags`
