### ISSUE TITLE
problems with use enter to create a tag

### ISSUE THREAD

**Issue by TutosHtml** [amsify42/jquery.amsify.suggestags#4]
hi, I was creating a form with the typical, an input text and a submit button. all in html tag form. the problem was that when you apply the class in jquery to the input and use the enter button to add the tag, instead of entering it, activate the submit button. this only happens when the elements are inside the  html tag form. please fix this, I do not know much about programming. Thank you

**Comment by amsify42** [comment]
Hi
So it is happening when it is inside form tag? Let me check the issue at my side.
It will be better if you can show some part of your code to identify the real issue.
Thank you.

**Comment by amsify42** [comment]
If you don't have textarea in your form you can use
`<form onkeypress="return event.keyCode != 13;">`

**Comment by eveperalta** [comment]
hi!
in mobile not working creating tabs, there is no enter key to activate the plugin by default the enter key changes to next[ https://developerweb.cl/registro_chef.html](url)
![WhatsApp Image 2020-04-27 at 12 09 03 PM](https://user-images.githubusercontent.com/20928308/80394536-fe7c3b00-887f-11ea-9e60-34c27b6eb75e.jpeg)
 please help !!!
