### ISSUE TITLE
Suggestion: processAjaxSuggestion

### ISSUE THREAD

**Issue by Madpeterz** [amsify42/jquery.amsify.suggestags#40]
the suggestions list should be emptyed and the new data used vs adding more onto the list

line: $.merge(_self.settings.suggestions, jsondata.suggestions);
change to: _self.settings.suggestions = jsondata.suggestions;

**Comment by amsify42** [comment]
But, In this way we will lose the existing items that are already set as default value.

**Comment by Madpeterz** [comment]
thats fine as the suggestions from the ajax are better no need to keep the old ones.
