### ISSUE TITLE
ajax call doesnt work 

### ISSUE THREAD

**Issue by Hretic** [amsify42/jquery.amsify.suggestags#41]
i noticed lots of issues are about this , but i went by the example still wont work 

here is my js code

```

    let  amsifySuggestags = new AmsifySuggestags($('#course-tags'));
    amsifySuggestags._settings({
        suggestionsAction : { url:'http://localhost/suggest.php' } ,
        type : 'amsify',
        whiteList:false
    })
    amsifySuggestags._init();

    for(var i in current_tags )
        amsifySuggestags.addTag(current_tags[i]);
```

my suggest.php

```
<?php

$suggestions 	= ['India', 'Pakistan', 'Nepal', 'UAE', 'Iran', 'Bangladesh'];
$data 			= [];
foreach($suggestions as $suggestion)
{
    $data[] = $suggestion;
}


header('Content-Type: application/json');
echo json_encode(['suggestions' => $data]);

?>
```

and in my console i see the response from backend 

`{"suggestions":["India","Pakistan","Nepal","UAE","Iran","Bangladesh"]}`

but the suggestion wont showup when i type

**Comment by amsify42** [comment]
It could be a styling issue, can you please send your html code as well?

**Comment by cquinoneso** [comment]
Same mistake 
js:
    console.log(tags);
    $('input[name="prod_tags"]').amsifySuggestags({
        suggestionsAction : {
           /* timeout: -1,
            minChars: 2,
            minChange: -1,*/
            type: 'GET',
            url: tags,
            beforeSend : function() {
                console.info('beforeSend');
            },
            success: function(data) {
                console.info('success');
            },
            error: function() {
                console.info('error');
            },
            complete: function(data) {
                console.info('complete');
            }
        }
    });

console:  {"existing":["jardin","martillo"],"term":"NADA"}

html:
<input type="text" class="form-control" name="prod_tags" id="prod_tags"/>

**Comment by cquinoneso** [comment]
Same mistake
js:
console.log(tags);
$('input[name="prod_tags"]').amsifySuggestags({
suggestionsAction : {
/* timeout: -1,
minChars: 2,
minChange: -1,*/
type: 'GET',
url: tags,
beforeSend : function() {
console.info('beforeSend');
},
success: function(data) {
console.info('success');
},
error: function() {
console.info('error');
},
complete: function(data) {
console.info('complete');
}
}
});

console: {"existing":["jardin","martillo"],"term":"NADA"}

html:
  `<input type="text" class="form-control" name="prod_tags" id="prod_tags"/>`

**Comment by amsify42** [comment]
> Same mistake
> js:
> 
> ```
>     console.log(tags);
>     $('input[name="prod_tags"]').amsifySuggestags({
>         suggestionsAction : {
>            /* timeout: -1,
>             minChars: 2,
>             minChange: -1,*/
>             type: 'GET',
>             url: tags,
>             beforeSend : function() {
>                 console.info('beforeSend');
>             },
>             success: function(data) {
>                 console.info('success');
>             },
>             error: function() {
>                 console.info('error');
>             },
>             complete: function(data) {
>                 console.info('complete');
>             }
>         }
>     });
> ```
> 
> console: {"existing":["jardin","martillo"],"term":"NADA"}
> 
> html:
> `<input type="text" class="form-control" name="prod_tags" id="prod_tags"/>`

I tried your code on my local machine, its working fine for me. Is this the list not showing to you as well?
