### ISSUE TITLE
Doesn't works properly with russian keyboard layout

### ISSUE THREAD

**Issue by Romer4ig** [amsify42/jquery.amsify.suggestags#42]
Russian letter "Б"(small "б") located on the same key as comma in english keyboard
Can you set confirm key optional or verify e.key exactly match ',' symbol?

**Comment by amsify42** [comment]
Okay I will try to do as suggested and let you know.

**Comment by amsify42** [comment]
I made some changes and publilshed the code, please update the code and check whether it is working as expected.

**Comment by Romer4ig** [comment]
Sorry, but you expression didn't help. If key not `,` and it was "б", keycode will be 188 in both variants.
More correct way i think `if(( keycode == '13') || (keycode == '188' && e.key && e.key == ',')) `

**Comment by amsify42** [comment]
Okay I will try to fix it.

**Comment by amsify42** [comment]
Made some changes, please check and confirm. Hope it will work this time.

**Comment by Romer4ig** [comment]
Thanks you, it's work
