### ISSUE TITLE
Disable check isSimilarText

### ISSUE THREAD

**Issue by Romer4ig** [amsify42/jquery.amsify.suggestags#43]
Can you set option for check similarity between tag and single suggest in list?
After you check returned true, autocomplete word from single suggest is not match tag what i want to enter, and i need sometimes remove one or more char to return word was before and enter tag what i want.

**Comment by amsify42** [comment]
Okay, I will add the option and let you know.

**Comment by amsify42** [comment]
I have added setting option with key name `checkSimilar`. By default, it is `true`, set it `false` if you want. Hope it will work as you expected.

**Comment by Romer4ig** [comment]
Thank you, it's working
