### ISSUE TITLE
Option to return values starting with input string

### ISSUE THREAD

**Issue by lharby** [amsify42/jquery.amsify.suggestags#44]
Is there an option to only return results that start with the input letter string?

We are sending an ajax request. Currently user inputs 'L'. Tags returned are: 

Filter1
Filter2

What I would like is (only tags that start with an 'L'):

Lambda
List1

**Comment by amsify42** [comment]
Okay, I will try to do it as suggested and update you once completed.

**Comment by amsify42** [comment]
I made the changes and showing suggestions after sorting. Code changes published in new version, please check and confirm.

**Comment by lharby** [comment]
Thank you I will pick this up next week.

**Comment by lharby** [comment]
Ha, sorry. As we are returning tags from an endpoint our team have agreed to handle this in the backend. However I think this feature will be useful to other users. I assume you have made it as an option rather than a default (although of course we will stick with our current version of the plugin)

**Comment by amsify42** [comment]
I made this sorting by default, sorting alphabetically if no search term is passed else sorting according to search term. Hope it will not cause any issue for you and I am closing this issue now.
