### ISSUE TITLE
on paste clear placeholder value 

### ISSUE THREAD

**Issue by pawanmanka** [amsify42/jquery.amsify.suggestags#46]
Hello,
when i paste tags in input area it make tags but not clear the pasted value so how can i remove after paste a string and make my tags and then remove the placeholder value
![Capture](https://user-images.githubusercontent.com/41562172/78453683-f7af3d80-76b0-11ea-8d4a-84c2693e3eb5.PNG)
i Did that on paste code
 $(this.selectors.sTagsInput).bind('paste', function(e){ 
            var str=e.originalEvent.clipboardData.getData('text');
            $(this).val('');
            var res;
            res=str.split(" ");
            var map="";
             var value = $.trim($(this).val().replace(/,/g , ''));
            var res_rmsp = res.filter(function (value) { return value !="" });
            $.each(res_rmsp,function(index,val){
              if(val[0] !="#" )
              {
               map+="#"+val;
              }
              else
              {
                 map+=val;
              }
            });              
             res=map.split("#");
             var data = res.filter(function (value) { return value !="" });
              $.each(data,function(index,val){
               _self.addTag(_self.getValue("#"+val));
              });
               if(_self.settings.showAllSuggestions) {
                _self.suggestWhiteList('', 0, true);
              }
            });

**Comment by amsify42** [comment]
I made some changes, to your code and added `setTimeout()` method to make the input empty. Hope it will work for you.
```js
$(this.selectors.sTagsInput).bind('paste', function(e){
	var str=e.originalEvent.clipboardData.getData('text');
	var res;
	res=str.split(" ");
	var map="";
	var value = $.trim($(this).val().replace(/,/g , ''));
	var res_rmsp = res.filter(function (value) { return value !="" });
	$.each(res_rmsp,function(index,val){
	if(val[0] !="#" )
	{
	map+="#"+val;
	}
	else
	{
	map+=val;
	}
	});
	res=map.split("#");
	var data = res.filter(function (value) { return value !="" });
	$.each(data,function(index,val){
	_self.addTag(_self.getValue("#"+val));
	});
	if(_self.settings.showAllSuggestions) {
	_self.suggestWhiteList('', 0, true);
	}
	setTimeout(function() {
		$(_self.selectors.sTagsInput).val('');
	}, 100);
});
```

**Comment by pawanmanka** [comment]
yes this is working . Thank you
