### ISSUE TITLE
Add support for comma escaping

### ISSUE THREAD

**Issue by quazardous** [amsify42/jquery.amsify.suggestags#52]
great work !

Supporting more character relative options would be nice (other separator than comma, separator escaping, etc)

**Comment by quazardous** [comment]
maybe by adding an optionnal tokenize callback and an onKeyEndOfTag callback returning true or false.

**Comment by amsify42** [comment]
There is already setting name `delimiters` , you can pass list of token by which you want to add tag.
Example:
```js
$('input[name="color"]').amsifySuggestags({
	delimiters: [';']
});
```
The above initialization will create tags when comma is entered. Hope it will work as expected.
