### ISSUE TITLE
allow custom match between suggestion and typing

### ISSUE THREAD

**Issue by quazardous** [amsify42/jquery.amsify.suggestags#54]
So I could match with tags and wildcards

**Comment by amsify42** [comment]
Okay, I will add callback option which will allow custom check for suggestions to appear.

**Comment by amsify42** [comment]
Added `suggestMatch` option in settings and published the changes. You can also check the README for more info about this. Hope it will be helpful.

**Comment by amsify42** [comment]
@quazardous  Closing this now. You can re open this if the mentioned solution does not work for you.
