### ISSUE TITLE
addTag don't eat objects

### ISSUE THREAD

**Issue by st-spark** [amsify42/jquery.amsify.suggestags#55]
Method .addTag takes only VALUE that string, integer or other simple data.

I tried to feed it with {tag: 'tagName', value: 666999} and it wont work. I fixed it with simple code, so there is purposed change:

-------------------

Old version of .getTag (): 
```
getTag : function(value) {
      if(this.settings.suggestions.length) {
        var tag = value;
        $.each(this.settings.suggestions, function(key, item){
          if(typeof item === 'object' && item.value == value) {
            tag = item.tag
            return false;
          }
          else if(item == value) {
            return false;
          }
        });
        return tag;
      }
      return value;
    },
```

New version of .getTag (): 
``` 
getTag : function(value) {
      var returnValue = value; // buffer var for value

      if(this.settings.suggestions.length) {
        var tag = value;
        $.each(this.settings.suggestions, function(key, item){
          if(typeof item === 'object' && item.value == value) {
            tag = item.tag
            return false;
          }
          else if(item == value) {
            return false;
          }
        });
        return tag;
      }
      // it seems that object mode works only when some suggestions set in settings
      else if (typeof value === 'object' && value.tag) {
        returnValue = value.tag;
      }
      
      return returnValue; // return buffer var, with right tagName
    },
```

-------------------

Old version of .addTag():
```
    addTag : function(value) {
      if(!value) {
        return;
      }
      var html = '<span class="'+this.classes.tagItem.substring(1)+'" data-val="'+value+'">'+this.getTag(value)+' '+this.setIcon()+'</span>';

    ...
```

New version of .addTag():
```
    addTag : function(value) {
      if(!value) {
        return;
      }

      // This temporary value need only to set data-val attribute below
      var temporaryValue = typeof value === 'object' && value.value ? value.value : value;

      var html = '<span class="'+this.classes.tagItem.substring(1)+'" data-val="'+temporaryValue+'">'+this.getTag(value)+' '+this.setIcon()+'</span>';

      // if value not exact  the same, then we need to re assign VALUE, we dont need to break code bellow
      if (temporaryValue !== value) {
        value = temporaryValue;
      }

    ...
```

Hope it helps, maybe there is more cleanier way to solve issue, but i just hammer it down in simpliest and fastest way.

Thank you for amaizing library o7

**Comment by amsify42** [comment]
Thank you.
I will check how these changes are working.

**Comment by amsify42** [comment]
I tried this object element with the existing code and it worked fine with both searching and adding the tag for this element.
```js
{tag: 'tagName', value: 666999}
```

**Comment by akzone** [comment]
> I tried this object element with the existing code and it worked fine with both searching and adding the tag for this element.
> 
> ```js
> {tag: 'tagName', value: 666999}
> ```

No it doesn't work, the input becomes "[object Objects]"

	amsifySuggestags = new AmsifySuggestags($('input[name="xxxxx"]'));
	amsifySuggestags._init();
	amsifySuggestags.addTag({
		tag: 'tagName',
		value: 666999
	});

**Comment by amsify42** [comment]
Actually `addTag` method does not take suggestion item object. It takes the actual value. To achieve what you are doing you have to do this
```js
amsifySuggestags = new AmsifySuggestags($('input[name="xxxxx"]'));
amsifySuggestags._settings({
	suggestions : [
		{
			tag: 'tagName',
			value: 666999
		}
	]
});
amsifySuggestags._init();
amsifySuggestags.addTag(666999);
```

**Comment by akzone** [comment]
> Actually `addTag` method does not take suggestion item object. It takes the actual value. To achieve what you are doing you have to do this
> 
> ```js
> amsifySuggestags = new AmsifySuggestags($('input[name="xxxxx"]'));
> amsifySuggestags._settings({
> 	suggestions : [
> 		{
> 			tag: 'tagName',
> 			value: 666999
> 		}
> 	]
> });
> amsifySuggestags._init();
> amsifySuggestags.addTag(666999);
> ```

Thank you, this works!
