### ISSUE TITLE
suggestionActions doesn't get triggered

### ISSUE THREAD

**Issue by kamado-tanjiro-usa** [amsify42/jquery.amsify.suggestags#56]
```
$('#update_tag').amsifySuggestags({
    suggestionsAction : {
		url: '/api/get_tags'
	}
});
```

doesn't work while

```
$('#update_tag').amsifySuggestags({
	suggestions: ['India', 'Pakistan', 'Nepal', 'UAE', 'Iran', 'Bangladesh']
});

```
does work. 

in the first example, nothing gets called at all

**Comment by kendosoul** [comment]
I see the issue now; it's trying to do string match among the suggestions and it'll break if it isn't ASCII

it works with ascii that actually matches. Is there any way to force it to display all suggestions?

**Comment by amsify42** [comment]
I checked with Non-ASCII Characters also with suggestions and it worked fine. Can you please mentioned the example you tried?

**Comment by amsify42** [comment]
@kamado-tanjiro-usa   Closing this now. You can re open this if it still does not work for you.
