### ISSUE TITLE
How to get input fields attributes data?

### ISSUE THREAD

**Issue by hassanuos** [amsify42/jquery.amsify.suggestags#57]
Like below I have multiple fields and I need to get some attributes to save tags data against that.

`<input type="text" data-user-id="'.$model->id.'" placeholder="اضف اشارة" class="form-control" name="color" value="'.$model->tags.'">`

I tried this but it does not return anything. It returns me undefined.

```
$('input[name="color"]').amsifySuggestags({
  type :'bootstrap',
  classes: ['bg-primary', 'bg-success', 'bg-danger', 'bg-warning', 'bg-info'],
  afterAdd:function(value) {
      console.log('after add =>',value, ' =>', $(this).data('user-id'));
  },
  afterRemove:function(value) {
      console.log('after remove =>', value);
  }

});
```

**Comment by amsify42** [comment]
You can simply do this, right?
```js
$('input[name="color"]').data('user-id');
or
$('input[name="color"]').attr('data-user-id');
```

**Comment by hassanuos** [comment]
@amsify42 it's fixed bro. actually I was using old library.

**Comment by hassanuos** [comment]
I am closing this now. Thanks for help.
