### ISSUE TITLE
Autocomplete Interferes With Typing

### ISSUE THREAD

**Issue by dlernstrom** [amsify42/jquery.amsify.suggestags#58]
Hello.  Great library.

One thing we are finding while we use the library is that the autocomplete seems to interfere with typing out the tag manually.  It seems like the resolution ought to be one or both of the below:

1 - Typically, an autocomplete library will have a wait time from the last keystroke before autocomplete is attempted.  I don't see in the library any mechanism for setting a timeout.
2 - When the autocomplete occurs, I've seen other libraries select the autocompleted text.  That way, if the user keeps typing, their keystrokes overwrite and blow away the portion of the text that was autocompleted.

Do either of these parameters exist in the library at all and I am just not seeing them defined anywhere?  If they do not exist, is there a PR process you follow for merging suggestions into your main trunk?  Are these changes that are compatible with your roadmap or should I fork the library for my unique usage?

**Comment by amsify42** [comment]
Hello,
Thank you.
Have you checked the settings like `timeout`, `minChars`, `minChange` under `suggestionAction` section?
https://github.com/amsify42/jquery.amsify.suggestags#suggestions-through-ajax

**Comment by dlernstrom** [comment]
Hi.
I studied out those settings and I don't really see how any of those settings will prevent the collisions while still offering the autocomplete capability we are after.

```
timeout - It is for cancelling the request after given specific seconds, default is -1
minChars - It is the minimum chars types before the first ajax hit, default is 2
minChange - It recall the ajax based on the minimum percentage chars changed compared to the string passed in last ajax call, default is -1
```

The setting that could be most beneficial is "timeout", however, I interpret this usage of timeout to be effectively how long to wait in the AJAX request to the server for the list of matches before the client library gives up.

An alternative "timeout" implementation, however, could allow the application to wait for no keystroke activity for some idle duration before attempting to autocomplete.  If we had this parameter and set it to something like 2 seconds, then the application wouldn't attempt autocomplete until the user stops typing.

Am I misreading the documentation for how the timeout parameter works as is implemented today?

**Comment by amsify42** [comment]
Okay, I will try to add this option and update you once the changes are published.

**Comment by dlernstrom** [comment]
That's fantastic.  We're looking forward to this change.  Fantastic library!

**Comment by amsify42** [comment]
Sorry for the very late response, I have added the `delay` option under `suggestionsAction` settings and published the changes. You can also check the same in readme. Hope it will work as expected.

**Comment by dlernstrom** [comment]
sweet!  that's very exciting!  will try today and report back.

**Comment by dlernstrom** [comment]
Hello - I had a chance to look over the change you contributed this morning.  Although I'm thrilled with the enhancement, it appears that the enhancement only affects the scenarios where the suggestions are loaded via Ajax request.  We use Suggestags 4 times in our infrastructure and in only one of them we fetch tags via Ajax.  In the remainder of the scenarios, we pre-populate the whiltelist during initial page load.  From what I can see, the delay option will not help us in those scenarios.

Can we get the "delay" capability moved to the area where the autocomplete occurs and then kill the timer on keystroke?

**Comment by amsify42** [comment]
Yes I added only from Ajax. Okay I will add for other case also, update and let you know.

**Comment by amsify42** [comment]
Updated and published. Please check, making the same config `delay` work for whitelist also.

**Comment by dlernstrom** [comment]
Top notch!  I love it!  Thank you!
One observation is that a spelling error for `whitelist` was introduced through this change, README.md line 135.

Again, many thanks!
Cheers,
David
