### ISSUE TITLE
tag limit not work

### ISSUE THREAD

**Issue by Tukizz** [amsify42/jquery.amsify.suggestags#6]
i set tagLimit : 3 or 5 in jquery, then when i input the tag value more than 3 or 5 the form input tag respond not block the value, how to fix that
this my jquery : 
`$(".tags").amsifySuggestags({
        tagLimit: 3
    });`

this my html tag :
`<input class="tags form-control" placeholder="add Tag" type="text" name="tags[]" multiple>`

thanks

**Comment by amsify42** [comment]
I didn't write the logic for it, that's why I didn't mention anything about tagLimit in readme or example files.
I will add the option and update the code as soon as possible.

**Comment by amsify42** [comment]
Added tagLimit option to the code and pushed. Hope it will help you.
