### ISSUE TITLE
Can we count tags in each row and show limit and show count.

### ISSUE THREAD

**Issue by hassanuos** [amsify42/jquery.amsify.suggestags#60]
I am trying to extend this library. I want here is to show tag count if tags more than 2. and rest I have to show remaining like for example.

Total Tags 5.
Display tags 2 and shows count  +3

Can we do that?

![image](https://user-images.githubusercontent.com/13483548/91959853-ddd25f00-ed11-11ea-8b26-85476fdf08ea.png)

**Comment by amsify42** [comment]
Currently it does not have such option, I will try to add the option and confirm here.

**Comment by hassanuos** [comment]
@amsify42 check your skype sir. I send you the video.

**Comment by amsify42** [comment]
Okay, I will check

**Comment by amsify42** [comment]
Sorry for the late response. I have added `showPlusAfter` setting and published the changes. You can see the same in readme as well. Hope it will work as expected for you.

**Comment by amsify42** [comment]
@hassanuos Closing this now. You can re open this if the mentioned solution does not work for you.
