### ISSUE TITLE
Delimiters dosen't work for default value

### ISSUE THREAD

**Issue by shaolinshaosson** [amsify42/jquery.amsify.suggestags#61]
It doesn't seem that delimiters is used when loading initial value?
Line 444:
`var items = $(this.selector).val().split(',');`
I had to change that to whatever delimiter I'm using
Initial value for me is "lorem;ipsum;argo"

**Comment by amsify42** [comment]
delimiters in the settings is for making text tag on that key hit. Its not for separating the tags in input value.
