### ISSUE TITLE
Show suggestions based on beginning letters only?

### ISSUE THREAD

**Issue by brian-dunning** [amsify42/jquery.amsify.suggestags#62]
If I type "br" it should suggest only words starting with br, not containing it like "abridged"

**Comment by amsify42** [comment]
Actually, It does both. It gets the tags with beginning letters then followed by the tags containing it.

**Comment by brian-dunning** [comment]
Any way to select an option to look only at the beginning of words? A person looking for "book" is more likely to type "bo" than "oo".

**Comment by amsify42** [comment]
If you want to show suggestion items based on custom matching, you can check `suggestMatch` callback option.
```txt
https://github.com/amsify42/jquery.amsify.suggestags#suggestmatch
```

**Comment by amsify42** [comment]
Closing this now. If you think no solution found, you can reopen it.
