### ISSUE TITLE
How to set default tag and value?

### ISSUE THREAD

**Issue by akzone** [amsify42/jquery.amsify.suggestags#63]
It's very useful for edit.

Thank you! This is awesome!

**Comment by jitenderbadoni** [comment]
Hi @amsify42 is this feature added.?

**Comment by amsify42** [comment]
> Hi @amsify42 is this feature added.?

Sorry for the very late reply. Are you asking about setting default value for suggestions having both tag and value?

**Comment by jitenderbadoni** [comment]
@amsify42 thats right. Although, i manage to do that. but if you can add this would be amazing.

**Comment by amsify42** [comment]
Do you want to set default value for the tag which is having different tag/value, then you must be having that tag in suggestions list during initialization.
Please check this to get the idea
```
https://github.com/amsify42/jquery.amsify.suggestags/issues/34#issuecomment-573776758
```
