### ISSUE TITLE
Execute the last typed tag before submitting?

### ISSUE THREAD

**Issue by brian-dunning** [amsify42/jquery.amsify.suggestags#64]
In testing of a live site, we're finding that many users will type their tags:
"yellow" (enter or comma) "red" (enter or comma) then "blue"
and go straight to the submit key, without hitting enter or comma after that last term, so the last term is not submitted and is lost. I poked around in jquery.amsify.suggestags.js looking for a function I could attach to onsubmit() that would execute whatever the comma or enter key does before submitting the form but I had no luck getting it to work. Is this possible?

**Comment by amsify42** [comment]
If we make the last tag without user being hitting enter or comma will be problematic because what if user enter some text and don't want to make it a tag. In that case user have to every time backspace the text entered to avoid an extra tag.

**Comment by brian-dunning** [comment]
In our testing, we found it was more common for people to type text in the field that they DO want, rather than typing unwanted text. 

- Brian

**Comment by amsify42** [comment]
Here is a sample code you can try to achieve what you mentioned.
```html
<form method="POST" id="my-form">
	<input type="text" class="form-control" name="colors"/>
	<input type="submit">			
</form>
```
Plugin initialization by instantiating it
```js
amsifySuggestags = new AmsifySuggestags($('input[name="colors"]'));
amsifySuggestags._settings({
	suggestions: ['Black', 'White', 'Red', 'Blue', 'Green', 'Orange']
});
amsifySuggestags._init();
```
Jquery workaround to handle and add last tag value after submit.
```js
$('#my-form').submit(function(e){
	e.preventDefault();
	var value = $(amsifySuggestags.selectors.sTagsInput).val();
	amsifySuggestags.addTag(value);
});
```
Hope it work for you and remember to add `this.submit();` after `amsifySuggestags.addTag(value);` if you want to submit the form after adding last tag like this.
```js
$('#my-form').submit(function(e){
	e.preventDefault();
	var value = $(amsifySuggestags.selectors.sTagsInput).val();
	amsifySuggestags.addTag(value);
        this.submit();
});
```

**Comment by amsify42** [comment]
Closing this now. You can reopen if the given solution is not appropriate.
