### ISSUE TITLE
Can we use POST with suggestionsAction to pass extra variables?

### ISSUE THREAD

**Issue by C4pt4inM** [amsify42/jquery.amsify.suggestags#69]
I am using suggestions based on a key. but there is no way  to pass that key. If I forcefully pass key like 
`https://api.website.com/getvalues?mykey=key123` 
then it combines amsify term with it like `key123?term=coffee`

**Comment by amsify42** [comment]
Sorry for the very late reply. For POST method, I think you can try something like this to add more data before sending
```js
$('input[name="toAjax"]').amsifySuggestags({
	suggestionsAction : {
		type: 'POST',
		url : 'https://api.website.com/getvalues',
		beforeSend : function(xhr, settings) {
			settings.data += '&'+$.param({mykey: 'key123'});
		}
	}
});
```

**Comment by amsify42** [comment]
I am closing this issue now. If you think the given solution does not work for you, you can reopen the issue again.
