### ISSUE TITLE
can I use ajax for get the sources?

### ISSUE THREAD

**Issue by winsonet** [amsify42/jquery.amsify.suggestags#7]
I want to dynamic get the source with ajax, can I do that?
thanks!

**Comment by amsify42** [comment]
You mean suggestions from ajax?

**Comment by winsonet** [comment]
Yes!

**Comment by amsify42** [comment]
Currently, it does not have such option.
I will add this option and update the code as soon as possible.

**Comment by winsonet** [comment]
Thanks a lot, that's will be great!

**Comment by amsify42** [comment]
Added suggestions through ajax option, check readme and example files for reference.
