### ISSUE TITLE
Mobile Support- tags not getting converted by , on android

### ISSUE THREAD

**Issue by Melywin** [amsify42/jquery.amsify.suggestags#70]
Hello amsify42, I am also facing the same issue but it is happening on android smartphone inputs, the key code entered in android for  `,` comma is showing 229 for virtual keypad on mobiles as well as for many other symbols too including` ;`  . Would be really helpful if it's fixed or could find a tweek for mobiles version. Thank you for a wonderful script.

_Originally posted by @Melywin in https://github.com/amsify42/jquery.amsify.suggestags/issues/47#issuecomment-805945759_

**Comment by amsify42** [comment]
I am doing some research on this issue, I think there is a problem while reading the key in Android browser specially Chrome.
I tried testing my plugin from my android phone with default browser and chrome browser and in both browsers, that key value is returning to 229 and the next problem is, its returning 229 for almost all keys.

I will try to find some solution for this and update.

**Comment by amsify42** [comment]
I fixed comma issue for mobile browser and published the changes. Please get the latest code or update the package and confirm.

**Comment by Melywin** [comment]
Thank You so much amisify42, its working Fine now.
