### ISSUE TITLE
Set tagLimit after init

### ISSUE THREAD

**Issue by dynagence** [amsify42/jquery.amsify.suggestags#71]
Hello,
Can I set/update the tagLimit setting after the init ?

**Comment by dynagence** [comment]
I found, just with :
amsifySuggestags._settings({
	tagLimit: 6
})

**Comment by amsify42** [comment]
Hello,
Yes you can update settings even after `_init` has been called
```js
amsifySuggestags = new AmsifySuggestags($('input[name="country"]'));
amsifySuggestags._init();

amsifySuggestags._settings({
	tagLimit: 6
});
```

**Comment by amsify42** [comment]
I am closing this issue now. You can reopen it if you think the solution is not found.
