### ISSUE TITLE
Ajax suggestions with relative path

### ISSUE THREAD

**Issue by flaviorib-dev** [amsify42/jquery.amsify.suggestags#73]
Hi everyone! Thanks for the great application!

I would like to know how I can use a relative path to the ajax resource script. Currently I can only use the full URL. Is that possible?

Thanks in advance

**Comment by amsify42** [comment]
If your base path is a simple domain, you can set even relative path in setting `suggestionsAction.url`

**Comment by flaviorib-dev** [comment]
Actually, the function "isAbsoluteURL" is always returning false, no mather the type of the path I inform. So, I had to change the function to return true.

**Comment by amsify42** [comment]
Okay I will look into it, try to fix and update.

**Comment by amsify42** [comment]
Sorry for the very late response. I have tested `isAbsoluteURL()` method with both absolute and relative url and it seems to be working. Can you please share what absolute url you tried and it didn't work?

**Comment by flaviorib-dev** [comment]
I just tested now with this latest update and I cal tell it's working. I have not seen any changes in the code related to the URLs, but the fact is that now I have not had to change anything so that the code works for me. Only to register, my urls are in localhost with a self made ssl certificate.

Thanks again for the great application.
