### ISSUE TITLE
Can we add dynamic background for Ajax suggestions?

### ISSUE THREAD

**Issue by MrMakaveli** [amsify42/jquery.amsify.suggestags#75]
Is there any way to add the background (color) dynamically to ajax pulled suggestions? What I'm trying to achieve is have all the existing suggestions that I get from my list (URL) with one background color and anything that is user inputted and not in the list with another color.
If this isn't possible, maybe consider it in future version as I think it might be helpful for others too. Thanks!

**Comment by amsify42** [comment]
Sorry for the very late reply. I have added the option to set class, color and background for each suggestion item if the item is object.
Please check this section for the new information
https://github.com/amsify42/jquery.amsify.suggestags#custom-stylings

**Comment by amsify42** [comment]
I am closing this issue now. If you think the option I added is not working properly, you can reopen this issue.

**Comment by RossHambleton** [comment]
How can I add backgrounds and colours using Ajax? I can add suggestions through Ajax, but not colours or backgrounds.
