### ISSUE TITLE
Ajax Custom Styling

### ISSUE THREAD

**Issue by RossHambleton** [amsify42/jquery.amsify.suggestags#76]
How can I add backgrounds and colours using Ajax? I can add suggestions through Ajax, but not colours or backgrounds.

**Comment by amsify42** [comment]
Please check this section for colors and background through ajax.
https://github.com/amsify42/jquery.amsify.suggestags#custom-stylings

**Comment by RossHambleton** [comment]
**This is what I've done:**
```

suggestionsAction : {
    timeout: -1,
    minChars:2,
    minChange:-1,
    delay: 100,
    type:'GET',
    url: 'https://mysite.co.uk/get_tags_list.php'
}
```
**This is what is returned:**

```
0: {tag: "West Midlands", value: "West Midlands", background: "White", color: "#2E8B57"}
1: {tag: "Cornwall", value: "Cornwall", background: "White", color: "#2E8B57"}
```

This works for the suggestions but the colours are not correct.

**Comment by amsify42** [comment]
Okay, I will check but make sure that your json response is in this format.
```json
{
	"suggestions": [
		{
			"tag": "Black",
			"value": 1,
			"background":"black",
			"color":"white"
		},
		{
			"tag": "White",
			"value": 2,
			"background":"white",
			"color":"black"
		}
	]
}
```

**Comment by RossHambleton** [comment]
This is the response, which I think looks correct. The tag part works fine, only the colours don't.

```
{
   "suggestions":[
      {
         "tag":"West Midlands",
         "value":"West Midlands",
         "background":"White",
         "color":"#2E8B57"
      },
      {
         "tag":"Cornwall",
         "value":"Cornwall",
         "background":"White",
         "color":"#2E8B57"
      },
      {
         "tag":"Bristol",
         "value":"Bristol",
         "background":"White",
         "color":"#2E8B57"
      }
   ]
}
```

**Comment by amsify42** [comment]
I have tested locally with the same data you mentioned of white background and different green shade colors and it worked.

Can you please check if you have updated version of this plugin.

**Comment by RossHambleton** [comment]
I'm not sure if it's up to date or not. But I've done this instead as a work around:

```
suggestions: <?php echo $tag_list; ?>,
backgrounds: <?php echo $tag_bg; ?>,
colors: <?php echo $tag_color; ?>
```

An SQL query provides the strings for each property.
