### ISSUE TITLE
Ajax and back end code

### ISSUE THREAD

**Issue by TEStaff** [amsify42/jquery.amsify.suggestags#77]
I am using c# to return this json from a database. The dropdown list is not triggering but the Json is returning

["adoptdontshop","America","Approvalratings","Atlanta","Based","Basedmemes","bitcoin",
"blackcat","blackcatclub","blackcatlove","blackcatlover","blackcats","blackcatsmatter",
"striketober","TheGreatResignation","TopNews","TPUSA","TPUSALive","transparency","trilliondollarbill",
"uni","USA","VaccineNews","WhiteHouse","Winsomesears"]

**Comment by amsify42** [comment]
Is your response in this format
```json
{
	"suggestions": [
		{
			"tag": "Black",
			"value": 1,
			"background":"black",
			"color":"white"
		},
		{
			"tag": "White",
			"value": 2,
			"background":"white",
			"color":"black"
		}
	]
}
```
and are you returning json header properly?

**Comment by TEStaff** [comment]
Thank you. I am new to C#, any sample of the above Json in C#?

**Comment by TEStaff** [comment]
I am now returning this but still not able to see it on the dropdown:

{
  "suggestions": [
    {
      "id": 33,
      "hashtag": "bitcoin"
    },
    {
      "id": 78,
      "hashtag": "trilliondollarbill"
    }
  ]
}

**Comment by TEStaff** [comment]
I am now returning this, but still not able to see it in the dropdown:

{
  "suggestions": [
    {
      "tag": "bitcoin",
      "value": 33
    },
    {
      "tag": "trilliondollarbill",
      "value": 78
    }
  ]
}

**Comment by amsify42** [comment]
I know very little about C#. This might help you figure out whether you are spending a proper json response or not.
https://stackoverflow.com/a/2423155

**Comment by TEStaff** [comment]
I am returning the correct Json. I am placing a copy of the returned data  in a div below for testing. This is my jquery code below. I am pulling data from a sql server and the result is not attaching to the dropdown:

```
$('input[name="toAjax"]').amsifySuggestags({
            suggestionsAction: {
                url: "/ajaxmethods/SearchHashtags/",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-TOKEN",
                        $('input:hidden[name="__RequestVerificationToken"]').val());                },
                type: 'GET',
                whiteList: true,
                dataType: "json",
                success: function (data) {
                    if (data != null) {
                     $("#MyFavoriteHashtags").append(data);
                    }
                },              
                error: function (response) {
                  //$("#MyFavoriteHashtags").html(response.responseText);
                },
                complete: function (data) {
                    console.info('complete');
                }    
            }
        });
```

![GIF 11-23-2021 1-36-23 PM](https://user-images.githubusercontent.com/94810517/143084341-29fb3416-c021-45b9-946a-bf546d64e068.gif)

**Comment by amsify42** [comment]
Can you please inspect your html elements in some browser and see whether any stylings are overriding and hiding those suggestions list.

**Comment by TEStaff** [comment]
I am not seeing any styling conflicts, but maybe you can identify the issue here. (still under development and will need a quick account since this is secured):

https://www.voicer.net/userpages/crud/ajaxpage

Your component works very well with the exception of this ajax/database call

**Comment by mitesh24shah24** [comment]
i am facing same issue as ajax not working.  for  me , its not initiating ajax call in network.
is there any minimum jquery and bootstrap version requirement ? 

below is my code snippet
----------------------------
$('input[name="toAjax"]').amsifySuggestags({
                            tagLimit: 3,
                            minChars: 1,
                            type: "GET",
                            url: site_url+'buy/testhello',
                            whiteList: true,
                            dataType: "json",
                            beforeSend : function() {
                                    console.info('beforeSend');
                            },
                            success: function(data) {
                                    
                                    console.info('success');console.log(data);
                            },
                            error: function() {
                                    console.info('error');
                            },
                            complete: function(data) {
                                    console.info('complete');
                            }
                    });

**Comment by amsify42** [comment]
@mitesh24shah24 
You need to pass those ajax settings under `suggestionAction` object. Please check here
https://github.com/amsify42/jquery.amsify.suggestags#suggestions-through-ajax
