### ISSUE TITLE
Idea for whitelist

### ISSUE THREAD

**Issue by github-rage** [amsify42/jquery.amsify.suggestags#8]
Hey,

I like the project, thanks for your work! It's my number one candidate to achieve what I have in mind. I got a feature request, though. I believe it'd be more convenient that when whitelist is enabled, and there's only one suggestion in the dropdown, then when enter is pressed, it would select that suggestion instead of dropping the typed text.

Let that be a partial match, or the entire word, but lowercase, for example. Now it's required to select it first by click or the arrow keys, and it will only turn it into label on a single enter if an exact match is typed.

If you'd prefer not to change the default mechanics, having an autoselect option for that would still be handy.

What do you think?

Thanks for your time!

**Comment by amsify42** [comment]
Thank you for your good suggestion. 
Its a good point that when whitelist is enabled, we should let the first match be entered as tag even if user entered partial text and hit Enter.

I will try to do it as early as I can and update the code.

**Comment by amsify42** [comment]
Added auto select option when only one item remain in suggestion and on both WhiteList as true or false setting.
When WhiteList is true, it will try to match 40%, and when it is false it will try to match 60% and auto select.
Hope it will help.
