### ISSUE TITLE
programmatically add and remove tags

### ISSUE THREAD

**Issue by iGeophysix** [amsify42/jquery.amsify.suggestags#9]
Hi. Is it possible to add a callable method to add and remove tags?
Or how can I do that already?

**Comment by amsify42** [comment]
Hi
Currently it does not have any method that can be called publicly.
I will try to add it and update here.

**Comment by amsify42** [comment]
I have changed the stricture of plugin to make the methods publicly available and use it with different approach as well.

Please check the readme content for this approach usage.
Hope it will be helpful for you.
